### ISSUE TITLE
خطا در نصب

### ISSUE THREAD

**Issue by prxpostern** [MortezaBashsiz/nipovpn#111]
nipovpn : Depends: libyaml-cpp0.8 but it is not installable
E: Unable to correct problems, you have held broken packages.

سلام روی سرور هتزنر نصب نمیشه و این خطا رو میده . وقتی میخوام پکیج مورد نیاز رو نصب کنم میگه وجود نداره !
apt install libyaml-cpp0.8
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libyaml-cpp0.8
E: Couldn't find any package by glob 'libyaml-cpp0.8'

چکار باید بکنم ؟

**Comment by MortezaBashsiz** [comment]
درود
لطفا بیشتر توضیح بدید

1. کدوم ورژن برنامه رو نصب میکنید
2. از کدام نسخه اوبونتو استفاده میکنید (حتما نسخه ۲۴.۰۴ باشه)

**Comment by prxpostern** [comment]
از قسمت release فایل deb  رو دان کردم نمیدونم میشه کدوم نسخه
اوبنتو من 22.04 هست . هیچ راهی نداره ؟

**Comment by MortezaBashsiz** [comment]
@prxpostern 

لطفا روی اوبونتو ۲۴.۰۴ نصب کنید
این برنامه با سایر نسخه ها سازگار نیست
سپاس
