### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by free-the-internet** [MortezaBashsiz/nipovpn#2]
Morteza, could you please add a little bit of docs about the lib you used for TLS/SSL and its signature? And, format of the packets you make to exchange control data between server and client?
Thanks for the valuable work you have done.

free-the-internet

**Comment by MortezaBashsiz** [comment]
It is not done yet, and I will add the full-document when it was ready

**Comment by aria3ppp** [comment]
@MortezaBashsiz please reopen this thread until the doc is ready

**Comment by aria3ppp** [comment]
btw i need a fast plug-and-play instruction
i really do not know where to start ://

**Comment by MortezaBashsiz** [comment]
You just need to download and install the .deb package
Then configure and restart the services
What else you supposed to have?

**Comment by aria3ppp** [comment]
@MortezaBashsiz i mean how agent knows where to send the http requests?

**Comment by aria3ppp** [comment]
@MortezaBashsiz ok my bad i should read the readme again
i think i have to change this line in `/etc/nipovpn/config.yaml`:
```yaml
agent:
  serverIp: 127.0.0.1
```
