### ISSUE TITLE
Cmake integration & project structure 

### ISSUE THREAD

**Issue by SirzechsLucifer666** [MortezaBashsiz/nipovpn#81]
I'd like to update the project by integrating CMake and reorganizing the files as mentioned in issue #59. Because the code is still tightly coupled, we can't do this all at once. So, I suggest starting by creating the new file structure, putting all files in the `core` submodule. Then, we can gradually move the independent classes into their correct modules.

**Comment by MortezaBashsiz** [comment]
Thanks for your contribution, I truly appreciate it.
I will wait for your pull requests.
